# Generated by Django 5.0.1 on 2024-02-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('date1', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
